project_id = "yvvnbmsbsrklajmoybwx"

[functions.realtime-voice]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.verify-prototype-access]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.verify-voice-guide-access]
verify_jwt = false
